-- Phase 1: Infrastructure Setup - Database, Schemas, Tables, Stages

-- Create core warehouse for agents
CREATE WAREHOUSE IF NOT EXISTS PAYERS_CC_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE;

-- Create primary database
CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;
USE DATABASE HEALTHCARE_DB;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS MEMBER_SCHEMA;
CREATE SCHEMA IF NOT EXISTS KNOWLEDGE_SCHEMA;
CREATE SCHEMA IF NOT EXISTS CHECKPOINT_SCHEMA;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- Member domain tables
CREATE TABLE IF NOT EXISTS MEMBER_SCHEMA.MEMBERS (
  member_id VARCHAR(20) PRIMARY KEY,
  dob DATE,
  name VARCHAR(100),
  plan_id VARCHAR(20),
  status VARCHAR(20),
  address VARCHAR(200),
  phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MEMBER_SCHEMA.CLAIMS (
  claim_id VARCHAR(20) PRIMARY KEY,
  member_id VARCHAR(20) REFERENCES MEMBER_SCHEMA.MEMBERS(member_id),
  claim_date DATE,
  service_type VARCHAR(50),
  amount DECIMAL(10,2),
  status VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MEMBER_SCHEMA.COVERAGE (
  plan_id VARCHAR(20) PRIMARY KEY,
  plan_name VARCHAR(100),
  deductible DECIMAL(10,2),
  copay_office DECIMAL(10,2),
  copay_er DECIMAL(10,2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Knowledge domain tables
CREATE TABLE IF NOT EXISTS KNOWLEDGE_SCHEMA.FAQS (
  faq_id VARCHAR(20) PRIMARY KEY,
  question TEXT,
  answer TEXT,
  category VARCHAR(50),
  updated_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_SCHEMA.POLICIES (
  policy_id VARCHAR(20) PRIMARY KEY,
  policy_name VARCHAR(100),
  content TEXT,
  version VARCHAR(10),
  effective_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_SCHEMA.CALL_TRANSCRIPTS (
  transcript_id VARCHAR(20) PRIMARY KEY,
  audio_id VARCHAR(20),
  member_id VARCHAR(20),
  call_date DATE,
  transcript_text TEXT,
  summary TEXT,
  sentiment VARIANT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS KNOWLEDGE_SCHEMA.AUDIO_FILES (
  audio_id VARCHAR(20) PRIMARY KEY,
  call_recording_path VARCHAR(200),
  member_id VARCHAR(20),
  call_date DATE,
  duration INT,
  uploaded_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Staging areas for raw assets
CREATE STAGE IF NOT EXISTS STAGING.AUDIO_STAGE;
CREATE STAGE IF NOT EXISTS STAGING.RAW_DATA;
